[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build/web"
  command = "if [ ! -d \"flutter\" ]; then git clone --depth 1 https://github.com/flutter/flutter.git -b stable; fi && ./flutter/bin/flutter build web --release"
